services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:4.11
    ports:
      - "4566:4566" 
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"             
    restart: unless-stopped 

volumes:
  localstack-data:
